### ISSUE TITLE
How to calibate

### ISSUE THREAD

**Issue by wujunyu94** [AlexKlimaj/LiPow-Firmware#27]
I made circuit board according to LiPow-Hardware by myself.
I plug type-c wire then it told "NOT CALIBRATED".After that i plugged 4s battery and type "cal" command, it told "Incorrect command parameter(s)".
Could u tell me the correct way to calibrate the adc, thank you.

Here is my debug message:

Starting LiPow.
Type Help to view a list of registered commands.
Firmware Version: 1.2

>Number of received Source PDOs: 4
PDO From Source: #0 PDO: 134320428  Voltage: 5000mV  Current: 3000mA  Power: 15000mW
PDO From Source: #1 PDO: 184620  Voltage: 9000mV  Current: 3000mA  Power: 27000mW
PDO From Source: #2 PDO: 307400  Voltage: 15000mV  Current: 2000mA  Power: 30000mW
PDO From Source: #3 PDO: 409750  Voltage: 20000mV  Current: 1500mA  Power: 30000mW
NOT CALIBRATED. Connect known good voltage to cells 1-4 and XT60 in the range of 3.3V - 4V and run cal command.
Then write then to flash with write_otp
cal
Incorrect command parameter(s).  Enter "help" to view a list of available commands.

[Press ENTER to execute the previous command again]

**Comment by AlexKlimaj** [comment]
Hi @wujunyu94 

You need to use a DC power supply of voltage reference in the range of 3.3V-4V attached to all cell inputs and the XT60 input in parallel. Use a multimeter to measure the voltage and in the LiPow terminal, enter the voltage with "cal 3890.2" . The cal command takes mV and is floating point type.

The cal command is temporary until you save it into one time programmable memory by entering "write_otp"

**Comment by wujunyu94** [comment]
Hi @AlexKlimaj 
Is that like this?
![IMG_0430](https://user-images.githubusercontent.com/15324417/67508417-8e6bdd00-f6c3-11e9-821b-1756d536cad2.jpg)

**Comment by AlexKlimaj** [comment]
It looks like you have a battery connected. You need to connect the same voltage to all the inputs. 

Wire all the balance inputs and the XT60 battery connector in parallel and connect a ~4.0V voltage source. 

![image](https://user-images.githubusercontent.com/2019539/67509644-ae15ed80-f650-11e9-8b9b-09fb8d08b831.png)

![image](https://user-images.githubusercontent.com/2019539/67509452-43fd4880-f650-11e9-81bf-9e4c8aef4911.png)

**Comment by wujunyu94** [comment]
I connected wires in your way.The input voltage is single cell of the battery: 3.88v.
And I typed "cal 3880":
![img001](https://user-images.githubusercontent.com/15324417/67512879-54530900-f6cc-11e9-8c48-347b822966b5.JPG)
Why scalar is so close？
According to the voltage dividing circuit in front of ADC, the voltage connected to the MCU will be different.
Is my result right?

**Comment by AlexKlimaj** [comment]
No, you should be seeing values like this.
![image](https://user-images.githubusercontent.com/2019539/67515017-110c8200-f65b-11e9-9268-b4f390a17f5e.png)

**Comment by AlexKlimaj** [comment]
@wujunyu94 Did you manage to calibrate you board?
